[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm run dev"
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild" 